fix for lyn woohooo
move to /bin/sh (tested on dash and ash) instead from /bin/b*sh (:vomiting_face:), added proper termcap colors instead of escape sequences, fixed the awful way the output was displayed (placed into a variable with cat and echoed with echo -e), fixed the broken switch (trans berry was getting displayed without --trans being specified)

diff --git a/lyfetch b/lyfetch
--- a/lyfetch
+++ b/lyfetch
@@ -1,50 +1,27 @@
-#!/bin/bash
+#!/bin/sh
 
 # Colours
-RED='\e[1;31m'
-GREEN='\e[1;32m'
-MAGENTA='\e[1;35m'
-YELLOW='\e[1;33m'
-NC='\e[0m'
+RED="$(tput setaf 1 bold)"
+GREEN="$(tput setaf 2 bold)"
+YELLOW="$(tput setaf 3 bold)"
+MAGENTA="$(tput setaf 5 bold)"
+NC="$(tput sgr0)"
 
-BLUE='\x1b[1;96m'
-PINK='\x1b[1;38;2;245;169;184m'
-WHITE='\x1b[1;97m'
+BLUE="$(tput setaf 14 bold)"
+PINK="$(tput setaf 217 bold)"
+WHITE="$(tput setaf 7 bold)"
 
 # Sys info
 NAME="$(whoami)@$(uname -n)"
-OS=$(awk -F= '$1 == "NAME" {gsub(/"/, "", $2); print $2}' /etc/os-release)
+OS="$(awk -F= '$1 == "NAME" {gsub(/"/, "", $2); print $2}' /etc/os-release)"
 KERNEL=$(uname -r)
 SHELL=$(basename $SHELL)
 UPTIME="$(uptime -p | sed 's/up //')"
 MEMORY="$(free -m | awk 'NR==2{print $3 "M / " $2 "M"}')"
 
-if [ ! -z "$1" ]; then
-  if [ "$1" != "--trans" ]; then
-    echo -e "${RED}ERROR:${NC} Unknown argument: ${1}, currently known arguments: --trans"
-    exit 1
-  fi
 
-OUTPUT="$(
-cat << BERRY
-${BLUE}      (    ((${NC}       ${MAGENTA}${NAME}${PINK}
-    ((  (((  ((     
-    ###(((((###${NC}     ${RED}OS:${NC}      ${OS}${WHITE}
-   ##%#######%##    ${RED}Kernel:${NC}  ${KERNEL}${WHITE}
-   ######%####%#${NC}    ${RED}Shell:${NC}   ${SHELL}${PINK}
-    ##%####%###     ${RED}Uptime:${NC}  ${UPTIME}${PINK}
-     #####%###      ${RED}Memory:${NC}  ${MEMORY}${BLUE}
-       #####
-         # ${NC}
-BERRY
-)"
-
-  echo -e "${OUTPUT}"
-  exit 0
-fi
-
-OUTPUT="$(
-cat << BERRY
+if [ -z "$1" ]
+then cat<<BERRY
 ${GREEN}      (    ((       ${MAGENTA}${NAME}${GREEN}
     ((  (((  ((     
     ${RED}###${GREEN}(((((${RED}###     ${RED}OS:${NC}      ${OS}${GREEN}
@@ -55,6 +32,17 @@ ${GREEN}      (    ((       ${MAGENTA}${NAME}${GREEN}
        ##### 
          #${NC}
 BERRY
-)"
-
-echo -e "${OUTPUT}"
+elif [ "$1" = "--trans" ]
+then cat<<BERRY
+${BLUE}      (    ((${NC}       ${MAGENTA}${NAME}${PINK}
+    ((  (((  ((     
+    ###(((((###${NC}     ${RED}OS:${NC}      ${OS}${WHITE}
+   ##%#######%##    ${RED}Kernel:${NC}  ${KERNEL}${WHITE}
+   ######%####%#${NC}    ${RED}Shell:${NC}   ${SHELL}${PINK}
+    ##%####%###     ${RED}Uptime:${NC}  ${UPTIME}${PINK}
+     #####%###      ${RED}Memory:${NC}  ${MEMORY}${BLUE}
+       #####
+         # ${NC}
+BERRY
+else printf "${RED}ERROR:${NC} Unknown argument: ${1}\nCurrently known arguments: --trans\n";exit 1
+fi
