Make art better, add trans flag

diff --git a/lyfetch b/lyfetch
--- a/lyfetch
+++ b/lyfetch
@@ -7,8 +7,12 @@ MAGENTA='\e[1;35m'
 YELLOW='\e[1;33m'
 NC='\e[0m'
 
+BLUE='\x1b[1;96m'
+PINK='\x1b[1;38;2;245;169;184m'
+WHITE='\x1b[1;97m'
+
 # Sys info
-NAME="$(whoami)@$(cat /etc/hostname)"
+NAME="$(whoami)@$(hostname)"
 OS=$(awk -F= '$1 == "NAME" {gsub(/"/, "", $2); print $2}' /etc/os-release)
 KERNEL=$(uname -r)
 SHELL=$(basename $SHELL)
@@ -19,12 +23,37 @@ read -r name    < /sys/devices/virtual/dmi/id/product_name
 read -r version < /sys/devices/virtual/dmi/id/product_version
 HOST="$name $version"
 
+if [ ! -z "$1" ]; then
+  if [ "$1" != "--trans" ]; then
+    echo -e "${RED}ERROR:${NC} Unknown argument: ${1}, known arguments: --trans"
+    exit 1
+  fi
+
 OUTPUT="$(
 cat << BERRY
-      ${GREEN}(    ((       ${MAGENTA}${NAME}${GREEN}
+${BLUE}      (    ((${NC}       ${MAGENTA}${NAME}${PINK}
+    ((  (((  ((     
+    ###(((((###${NC}     ${RED}OS:${NC}      ${OS}${WHITE}
+   ##%#######%##    ${RED}Host:${NC}    ${HOST}${WHITE}
+   ######%####%#${NC}    ${RED}Kernel:${NC}  ${KERNEL}${PINK}
+    ##%####%###     ${RED}Shell:${NC}   ${SHELL}${PINK}
+     ####%####      ${RED}Uptime:${NC}  ${UPTIME}${BLUE}
+       #####        ${RED}Memory:${NC}  ${MEMORY}${BLUE}
+         # ${NC}
+BERRY
+)"
+
+  echo -e "${OUTPUT}"
+  exit 0
+fi
+
+OUTPUT="$(
+cat << BERRY
+     ${GREEN}((     (((
+      (    ((       ${MAGENTA}${NAME}${GREEN}
     ((  (((  ((     
     ${RED}###${GREEN}(((((${RED}###     ${RED}OS:${NC}      ${OS}${GREEN}
-   ${RED}##${YELLOW}%${RED}##${GREEN}((${RED}###${YELLOW}%${RED}##    ${RED}Host:${NC}    ${HOST}${RED}
+   ${RED}##${YELLOW}%${RED}#######${YELLOW}%${RED}##    ${RED}Host:${NC}    ${HOST}${RED}
    ######${YELLOW}%${RED}####${YELLOW}%${RED}#    ${RED}Kernel:${NC}  ${KERNEL}${RED}
     ##${YELLOW}%${RED}####${YELLOW}%${RED}###     ${RED}Shell:${NC}   ${SHELL}${RED}
      ####${YELLOW}%${RED}####      ${RED}Uptime:${NC}  ${UPTIME}${RED}
